name: Build Tauri Windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-windows:
    name: Build Windows bundles
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Rust Windows target
        run: rustup target add x86_64-pc-windows-msvc

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build --if-present

      - name: Build Tauri (Windows)
        env:
          CI: true
        run: npx tauri build

      - name: Upload tauri bundles
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows-bundles
          path: |
            src-tauri/target/release/bundle/**
